export const ADD_BUN = 'ADD_BUN';
export const ADD_INGREDIENTS = 'ADD_INGREDIENTS';
export const MOVE_INGREDIENT = 'MOVE_INGREDIENT';
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT';
export const SET_TOTAL_PRICE = "SET_TOTAL_PRICE";
export const CLEAR_CART = "CLEAR_CART";