export const WS_PROFILE_ORDERS_CONNECTION_START = 'WS_PROFILE_ORDERS_CONNECTION_START';
export const WS_PROFILE_ORDERS_SEND_MESSAGE = 'WS_PROFILE_ORDERS_SEND_MESSAGE';
export const WS_PROFILE_ORDERS_CONNECTION_SUCCESS = 'WS_PROFILE_ORDERS_CONNECTION_SUCCESS';
export const WS_PROFILE_ORDERS_CONNECTION_CLOSED = 'WS_PROFILE_ORDERS_CONNECTION_CLOSED';
export const WS_PROFILE_ORDERS_CONNECTION_ERROR = 'WS_PROFILE_ORDERS_CONNECTION_ERROR';
export const WS_PROFILE_ORDERS_GET_MESSAGE = 'WS_PROFILE_ORDERS_GET_MESSAGE';

export const OPEN_DETAILS = 'OPEN_DETAILS';
export const CLOSE_DETAILS = 'CLOSE_DETAILS';
